### ISSUE TITLE
Illustration of the generated samples

### ISSUE THREAD

**Issue by zhangxin-xd** [ControlNet/AV-Deepfake1M#2]
Hi, thank you for your excellent work!

I want to see what the manipulated samples look like, but it seems that I need to download the entire dataset. 

Could you please share some examples here? 

Thank you! Looking forward to your response.

**Comment by XiXiRuPan** [comment]
Sorry Could you please show me how to download the entire dataset? Thank you

**Comment by ControlNet** [comment]
We're hosting [1M-Deepfakes Detection Challenge](https://deepfakes1m.github.io/) at ACM MM 2024. Please requeast the dataset there.

**Comment by ControlNet** [comment]
We shared a demo video for for the dataset samples. Please refer to the supplementary video in the [ACM paper page](https://dl.acm.org/doi/10.1145/3664647.3680795).
