### ISSUE TITLE
Request for Guidance on Extracting Visual Features using InternVideo

### ISSUE THREAD

**Issue by Myblackcat0216** [ControlNet/AV-Deepfake1M#5]
Thank you very much for your great work. How do you extract visual features with InternVideo? I can't find detailed procedures and steps on the official website of InternVideo. Any assistance would be greatly appreciated. Thank you.

**Comment by ControlNet** [comment]
Hi @Myblackcat0216 , I think you can have a look to the code here. https://github.com/OpenGVLab/InternVideo/tree/main/InternVideo1/Pretrain/VideoMAE
